'use client'
import { useState } from 'react'
export function LyricsEditor({initialLyrics,songTitle,genre,onSave}:{initialLyrics:string;songTitle:string;genre:string;onSave:(l:string)=>void}) {
  const [lyrics,setLyrics]=useState(initialLyrics||''); const [suggestions,setSuggestions]=useState<string[]>([]); const [isGen,setIsGen]=useState(false)
  const analyze=(t:string)=>{const lines=t.split('\n').filter(l=>l.trim());const hasRhyme=lines.length>=2;return{lines:lines.length,hasRhyme,score:Math.min(100,(lines.length>=4?30:0)+(hasRhyme?40:0)+30)}}
  const gen=()=>{setIsGen(true);setTimeout(()=>{setSuggestions(['Y el beat sigue sonando en mi corazon','Luces de neon iluminan la noche','Bolero-House ritmo que nos une','Tu frecuencia es mi melodia']);setIsGen(false)},1500)}
  const a=analyze(lyrics)
  return (<div className="bg-black/50 p-6 rounded-2xl border border-c8l-gold/30"><div className="flex justify-between items-center mb-4"><h3 className="text-xl font-bold text-c8l-gold">📝 Editor Letra IA</h3><span className={`text-xs px-2 py-0.5 rounded-full ${a.score>=70?'bg-green-600/20 text-green-400':'bg-yellow-600/20 text-yellow-400'}`}>Score:{a.score}/100</span></div><div className="grid lg:grid-cols-3 gap-4"><div className="lg:col-span-2"><textarea value={lyrics} onChange={e=>setLyrics(e.target.value)} className="w-full bg-black border border-gray-700 rounded-lg p-4 text-white font-mono text-sm min-h-[300px] resize-none focus:outline-none focus:border-c8l-gold" placeholder="[Verso 1]\nEscribe..." /><div className="flex gap-2 mt-2"><button onClick={gen} disabled={isGen} className="px-4 py-2 bg-purple-600/20 text-purple-400 text-sm font-bold rounded-lg disabled:opacity-50">{isGen?'🌀...':'✨ IA'}</button><button onClick={()=>onSave(lyrics)} className="px-4 py-2 bg-c8l-gold text-black text-sm font-bold rounded-lg">💾</button></div></div><div className="space-y-3"><div className="bg-black/30 p-3 rounded-lg border border-gray-800 text-sm"><div className="flex justify-between"><span className="text-gray-400">Lineas</span><span>{a.lines}</span></div><div className="flex justify-between"><span className="text-gray-400">Rima</span><span className={a.hasRhyme?'text-green-400':'text-yellow-400'}>{a.hasRhyme?'✅':'⚠️'}</span></div></div>{suggestions.length>0&&<div className="bg-black/30 p-3 rounded-lg border border-purple-600/30 space-y-1">{suggestions.map((s,i)=><button key={i} onClick={()=>{setLyrics(l=>l+'\n'+s);setSuggestions([])}} className="w-full text-left text-xs text-gray-300 p-1.5 rounded hover:bg-purple-600/20">🪄 {s}</button>)}</div>}</div></div></div>)
}
