'use client'
import { useState, useEffect, useRef } from 'react'
const generateCard = () => { const ranges: Record<string,[number,number]> = {B:[1,15],I:[16,30],N:[31,45],G:[46,60],O:[61,75]}; const letters = ['B','I','N','G','O']; const card: any[][] = []; for(let r=0;r<5;r++){const row:any[]=[];for(let c=0;c<5;c++){const l=letters[c];const[min,max]=ranges[l];const num=min+Math.floor(Math.random()*(max-min+1));row.push({number:num,letter:l,marked:r===2&&c===2,isFree:r===2&&c===2})}card.push(row)} return card }
interface Props { coins: number; onCoinsChange: (c:number) => void }
export default function Bingo3D({ coins, onCoinsChange }: Props) {
  const [card, setCard] = useState(generateCard()); const [called, setCalled] = useState<string[]>([]); const [ball, setBall] = useState<{letter:string;number:number}|null>(null); const [showBall, setShowBall] = useState(false); const [lines, setLines] = useState(0); const [isBingo, setIsBingo] = useState(false); const [win, setWin] = useState(0); const [started, setStarted] = useState(false); const [spin, setSpin] = useState(0); const [particles, setParticles] = useState<{x:number;y:number;color:string;size:number}[]>([]); const iv = useRef<any>(null)
  useEffect(() => { const t = setInterval(() => setSpin(p=>p+3), 30); return () => clearInterval(t) }, [])
  const explode = (n:number, colors:string[]) => { const p = Array.from({length:n},()=>({x:30+Math.random()*40,y:20+Math.random()*40,color:colors[Math.floor(Math.random()*colors.length)],size:4+Math.random()*12})); setParticles(prev=>[...prev,...p]); setTimeout(()=>setParticles(prev=>prev.slice(n)),3000) }
  const callNum = () => { if(isBingo) return; const ls=['B','I','N','G','O']; const rng:Record<string,[number,number]>={B:[1,15],I:[16,30],N:[31,45],G:[46,60],O:[61,75]}; const l=ls[Math.floor(Math.random()*5)]; const[mn,mx]=rng[l]; const num=mn+Math.floor(Math.random()*(mx-mn+1)); const key=`${l}${num}`; if(called.includes(key)) return; setBall({letter:l,number:num}); setShowBall(true); setCalled(p=>[...p,key]); const nc=card.map(r=>r.map(c=>c.letter===l&&c.number===num?{...c,marked:true}:c)); setCard(nc); checkL(nc); setTimeout(()=>setShowBall(false),2000) }
  const checkL = (c:typeof card) => { let ln=0; for(let r=0;r<5;r++) if(c[r].every(x=>x.marked)) ln++; for(let col=0;col<5;col++) if(c.every(r=>r[col].marked)) ln++; if(c.every((r,i)=>r[i].marked)) ln++; if(c.every((r,i)=>r[4-i].marked)) ln++; if(ln>lines) explode(30,['#D4AF37','#FF69B4','#00F3FF']); setLines(ln); if(ln>=5&&!isBingo){const w=500+ln*200+Math.floor(Math.random()*2000);setIsBingo(true);setWin(w);onCoinsChange(coins+w);explode(100,['#D4AF37','#FF69B4','#00F3FF','#8A2BE2'])} }
  const start = () => { if(coins<50) return; onCoinsChange(coins-50); setStarted(true); setIsBingo(false); setLines(0); setCalled([]); setCard(generateCard()); setWin(0); iv.current=setInterval(callNum,2500+Math.random()*1500) }
  const stop = () => { if(iv.current) clearInterval(iv.current); setStarted(false) }
  useEffect(()=>()=>{if(iv.current) clearInterval(iv.current)},[])
  return (
    <div className="relative min-h-[80vh] bg-gradient-to-br from-black via-purple-950/30 to-black rounded-2xl overflow-hidden border-2 border-c8l-gold/30">
      <div className="absolute inset-0 pointer-events-none overflow-hidden">{Array.from({length:40}).map((_,i)=><div key={i} className="absolute w-1 h-1 rounded-full animate-float" style={{left:`${Math.random()*100}%`,top:`${Math.random()*100}%`,background:i%3===0?'#D4AF37':i%3===1?'#8A2BE2':'#00F3FF',opacity:0.2+Math.random()*0.3,animationDelay:`${Math.random()*5}s`,animationDuration:`${4+Math.random()*6}s`}} />)}{particles.map((p,i)=><div key={`p${i}`} className="absolute rounded-full animate-ping" style={{left:`${p.x}%`,top:`${p.y}%`,width:p.size,height:p.size,background:p.color,opacity:0.8}} />)}</div>
      <div className="relative z-10 p-6">
        <div className="flex justify-between items-center mb-6"><div><h1 className="text-4xl font-black neon-gold">🎰 QUANTUM BINGO 3D</h1><p className="text-xs text-gray-400 mt-1">RTP 97.3% | Jackpot | 3D</p></div><div className="glass px-4 py-2 rounded-full border border-c8l-gold/50"><span className="text-c8l-gold font-mono font-bold">💰 {coins.toLocaleString()}</span></div></div>
        <div className="grid grid-cols-4 gap-3 mb-6">{[{v:lines,l:'Lineas',c:'text-c8l-gold'},{v:called.length,l:'Bolas',c:'text-purple-400'},{v:isBingo?'🎉':`${Math.min(99,Math.floor(lines/5*100))}%`,l:'Progreso',c:'text-c8l-cyan'},{v:win>0?`+${win}`:'0',l:'Premio',c:'text-c8l-pink'}].map((s,i)=><div key={i} className="glass rounded-lg p-3 text-center"><div className={`text-2xl font-black ${s.c}`}>{s.v}</div><div className="text-[10px] text-gray-500 uppercase">{s.l}</div></div>)}</div>
        {showBall && ball && <div className="absolute top-32 right-8 z-30 animate-bounce"><div className="w-20 h-20 rounded-full flex items-center justify-center" style={{background:'radial-gradient(circle at 30% 30%,#FFD700,#D4AF37,#8B6914)',boxShadow:'0 0 40px #D4AF37',transform:`rotate(${spin}deg)`}}><div className="text-center"><div className="text-[10px] font-bold text-black/70">{ball.letter}</div><div className="text-xl font-black text-black">{ball.number}</div></div></div></div>}
        <div className="flex justify-center mb-6" style={{perspective:'1000px'}}><div style={{transform:'rotateX(5deg) rotateY(-2deg)',transformStyle:'preserve-3d'}}><div className="grid grid-cols-5 gap-1 mb-1">{['B','I','N','G','O'].map(l=><div key={l} className="w-14 h-9 flex items-center justify-center rounded-t-lg text-lg font-black" style={{background:'linear-gradient(135deg,#D4AF37,#FFD700)',color:'#000'}}>{l}</div>)}</div><div className="grid grid-cols-5 gap-1">{card.map((row,ri)=>row.map((cell,ci)=><div key={`${ri}-${ci}`} className={`w-14 h-14 flex flex-col items-center justify-center rounded-lg font-bold transition-all duration-300 relative overflow-hidden ${cell.isFree?'bg-gradient-to-br from-purple-600 to-purple-900 border-2 border-purple-400':cell.marked?'border-2 border-c8l-gold scale-105':'bg-gray-900/80 border border-gray-700 hover:border-c8l-gold/50 hover:scale-105'}`} style={cell.marked&&!cell.isFree?{background:'linear-gradient(135deg,#D4AF37,#B8860B)',color:'#000',boxShadow:'0 0 15px #D4AF37'}:{}}>{cell.marked&&!cell.isFree&&<div className="absolute inset-0 rounded-lg animate-pulse" style={{background:'radial-gradient(circle,#D4AF3733,transparent)'}} />}{cell.isFree?<span className="text-xl">⭐</span>:<><span className="text-[9px] text-gray-500">{cell.letter}</span><span className={`text-base font-black ${cell.marked?'text-black':''}`}>{cell.number}</span></>}</div>))}</div></div></div>
        {isBingo&&<div className="absolute inset-0 z-40 flex items-center justify-center pointer-events-none"><div className="text-center animate-bounce"><div className="text-7xl font-black neon-gold" style={{textShadow:'0 0 20px #D4AF37,0 0 40px #D4AF37,0 0 80px #FFD700'}}>🎉 BINGO! 🎉</div><div className="text-3xl font-bold text-white">+{win} 💰</div></div></div>}
        <div className="flex gap-4">{!started?<button onClick={start} disabled={coins<50} className="flex-1 py-4 rounded-xl font-black text-xl hover:scale-105 transition-all disabled:opacity-50" style={{background:'linear-gradient(135deg,#D4AF37,#FF69B4)',color:'#000',boxShadow:'0 4px 30px #D4AF3744'}}>🎰 JUGAR (50 Coins)</button>:<button onClick={stop} className="flex-1 py-4 bg-red-600 text-white rounded-xl font-black text-xl hover:bg-red-500 hover:scale-105 transition-all">🛑 TERMINAR</button>}</div>
        <div className="mt-4 glass rounded-xl p-4 border border-gray-800"><div className="text-xs text-gray-400 mb-2 uppercase">Ultimas bolas</div><div className="flex gap-2 flex-wrap">{called.slice(-12).map((n,i)=><div key={i} className="w-9 h-9 rounded-full flex items-center justify-center text-[10px] font-bold border" style={{background:i===called.slice(-12).length-1?'linear-gradient(135deg,#D4AF37,#FFD700)':'#111',borderColor:i===called.slice(-12).length-1?'#D4AF37':'#333',color:i===called.slice(-12).length-1?'#000':'#D4AF37'}}>{n}</div>)}{called.length===0&&<span className="text-gray-600 text-sm">Inicia partida</span>}</div></div>
        <div className="mt-4 glass rounded-xl p-4 border border-c8l-gold/20"><div className="flex justify-between items-center"><span className="text-xs text-gray-400 uppercase">🏆 Jackpot</span><span className="text-xl font-black text-c8l-gold neon-gold">25,000 C8L</span></div><div className="h-2 bg-gray-800 rounded-full mt-2 overflow-hidden"><div className="h-full rounded-full animate-pulse" style={{width:'73%',background:'linear-gradient(90deg,#D4AF37,#FF69B4,#00F3FF)'}} /></div></div>
      </div>
    </div>
  )
}
